id=conversion-json-hl7
name=JSON HL7 CONVERSION
version=${project.version}
description=${project.description}
class=io.gravitee.policy.json_hl7.MainPolicy
type=policy
category=transformation
icon=icon.svg
proxy=REQUEST, RESPONSE
